# Generated by Django 2.2.1 on 2019-05-27 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_availability', models.BooleanField(default=True)),
                ('doctor_specialisation', models.CharField(max_length=200)),
                ('doctor_shift_slot1_from', models.TimeField(null=True)),
                ('doctor_shift_slot1_to', models.TimeField(null=True)),
                ('doctor_shift_slot2_from', models.TimeField(null=True)),
                ('doctor_shift_slot2_to', models.TimeField(null=True)),
                ('doctor_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, null=True)),
                ('patient_age', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('patient_DOB', models.DateField(null=True)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('patient_new', models.BooleanField(default=True)),
                ('insurance', models.CharField(max_length=100, null=True)),
                ('patient_height', models.IntegerField(null=True)),
                ('patient_weight', models.IntegerField(null=True)),
                ('patient_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], default='F', max_length=1)),
                ('criticality', models.CharField(max_length=20)),
                ('reason_for_consultation', models.CharField(max_length=300, null=True)),
                ('appointment_date_time', models.DateTimeField(null=True)),
                ('appointment_form_submission_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
