# Generated by Django 2.2.1 on 2019-06-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='doctorDetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.DoctorDetails'),
            preserve_default=False,
        ),
    ]
