# Generated by Django 2.2.1 on 2019-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_patientdetails_doctordetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_shift_slot1_from',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_shift_slot1_to',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_shift_slot2_from',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='doctor_shift_slot2_to',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='is_Doctor_servicing',
            field=models.BooleanField(default=True),
        ),
    ]
