# Generated by Django 2.2.1 on 2019-06-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_doctordetails_remaining_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='is_Doctor_servicing',
            new_name='is_Doctor_serving',
        ),
    ]
