# Generated by Django 2.2.1 on 2019-06-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190605_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='is_Doctor_serving',
            new_name='is_Doctor_servicing',
        ),
    ]
