# Generated by Django 2.2.1 on 2019-06-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190605_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='appointment_date_time',
        ),
    ]
